"""empty message

Revision ID: 7a34d0d2eae0
Revises: 
Create Date: 2023-09-15 10:53:41.253450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a34d0d2eae0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fabrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(length=64), nullable=True),
    sa.Column('size', sa.String(length=1), nullable=True),
    sa.Column('stock_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fabric_id', sa.Integer(), nullable=True),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabrics.id'], ),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('frames')
    op.drop_table('fabrics')
    # ### end Alembic commands ###
